Session/7
fa0311/flutter-training pull request #23
Opened 2024-08-06 06:31 UTC by fa0311

## 課題

close #8

## 対応箇所

- [freezed] を利用して、独自のクラスから API のリクエストを作成する
- [freezed] を利用して、API のレスポンスを独自のクラスに変換する

## 動作

動作に変更はありません

2024-08-07 08:33 UTC, fa0311 commented on lib/domain/weather_service.dart
> +      throw WeatherInvalidResponseException();
ペアプロ時に指摘された通り、エラーハンドリングの実装を修正する必要がありそう

2024-08-08 06:16 UTC, fa0311 commented on lib/domain/weather_service.dart
> +    return jsonEncode(model.toJson());
シリアライズでの、`try catch` は削除しました
Freezed や Dart の標準ライブラリに起因するエラーが万が一発生した際は `catch` せずに、エラーを伝播した方が適切だと思ったからです

2024-08-08 06:21 UTC, fa0311 commented on lib/model/weather_model.dart
> +  @JsonSerializable(fieldRename: FieldRename.snake)
このプロジェクトで定義されている全てのModelは、`@JsonSerializable(fieldRename: FieldRename.snake)` ですが `build.yaml` には書いていません
他のAPIが増えた際に、それが`@JsonSerializable(fieldRename: FieldRename.snake)`だとは限らないからです

(ディレクトリごとに `build.yaml` のオプションを変えたりする方法もありそうですが...)

2024-08-08 06:25 UTC, fa0311 commented on lib/view/weather.dart
> +      final model = WeatherParameterModel(area: 'tokyo', date: DateTime.now());
`WeatherParameterModel` の default value にここら辺のパラメータを書きたかったが、DateTime が `constants` な値じゃないので少しややこしそう

大きなメリットもないと思うので、これでいいと思うが少し気になる

2024-08-08 07:35 UTC, fa0311 commented on analysis_options.yaml
> +    invalid_annotation_target: ignore
https://github.com/rrousselGit/freezed/issues/488#issuecomment-894358980
に書いてあるとおり、invalid_annotation_target の警告を無効にしています

2024-08-08 08:08 UTC, fa0311 commented on lib/model/weather_model.dart
> +  @JsonSerializable(fieldRename: FieldRename.snake)
`build.yaml` に書く方法にしました

2024-08-08 08:14 UTC, blendthink reviewed
@fa0311 CC: @Yamasaki-pan961 
もしかするとペア作業ですでに話されているかもですが、少しだけコメントさせていただきました！
ご確認していただけると幸いです 🙏

2024-08-08 08:14 UTC, blendthink commented on lib/model/weather_model.dart
> +      _$WeatherParameterModelFromJson(json);
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey) 
あくまで参考程度にですので、修正は不要です！

リクエストパラメータ用のモデルとして用意していることから厳密には `fromJson` は不要なので削除したいと思うかもしれません。ただ、 `fromJson` 部分を削除するだけだと `toJson` も削除されてしまって困るかもしれません。
そのときには次のようにすると `toJson` のみ作成してくれます。

```dart
@Freezed(toJson: true)
class WeatherParameterModel with _$WeatherParameterModel {
  const factory WeatherParameterModel({
    required String area,
    required DateTime date,
  }) = _WeatherParameterModel;
}
```

2024-08-08 08:14 UTC, blendthink commented on analysis_options.yaml
> +    invalid_annotation_target: ignore
![nits-badge](https://img.shields.io/badge/review-nits-orange.svg) 
↓の対応でこの指定が削除されてしまっていますのでご確認お願いします。
https://github.com/fa0311/flutter-training/pull/23/commits/9849c52e2a80e9e2d8e48caa5f33400842000a9a

![next-badge](https://img.shields.io/badge/review-next-blueviolet) 
あと、なぜこの指定をしているのか、他の開発者だったりレビュアーだったりがぱっと分かるようにコメントを書いておくとより良さそうです！

2024-08-08 08:20 UTC, Yamasaki-pan961 reviewed
一旦コメントします

2024-08-08 08:20 UTC, Yamasaki-pan961 commented on analysis_options.yaml
> +    invalid_annotation_target: ignore
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)
本来クラスにしか付けられないアノテーションをFreezedのJsonSerializableのオプションをつける時に無効化する必要がある

2024-08-08 08:20 UTC, Yamasaki-pan961 commented on .gitattributes
> +*.gen.dart linguist-generated=true
![good-badge](https://img.shields.io/badge/Review-Good-yellow)
この設定レビュー時にめちゃめちゃ助かります

2024-08-08 08:30 UTC, fa0311 commented on lib/model/weather_model.dart
> +      _$WeatherParameterModelFromJson(json);
ありがとうございます！オプションについて知りませんでした！
[7056bfb84d20e061bfa19b1b8fae26bc6136f3bd](https://github.com/fa0311/flutter-training/commit/7056bfb84d20e061bfa19b1b8fae26bc6136f3bd) で対応しました

2024-08-09 03:40 UTC, Yamasaki-pan961 approved these changes
![good-badge](https://img.shields.io/badge/Review-Good-yellow)
基礎的なFreezed + JsonSerializableの使い方はバッチリだと思いました！

![nits-badge](https://img.shields.io/badge/review-nits-pink)
細かいところを指摘しているのでご確認お願いします！

2024-08-09 03:40 UTC, Yamasaki-pan961 commented on lib/view/weather.dart
> +            content: message != null ? Text(message) : null,
![good-badge](https://img.shields.io/badge/Review-Good-yellow)
😍

2024-08-09 03:40 UTC, Yamasaki-pan961 commented on lib/model/weather_model.dart
> +}
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)
Weatherのモデルと同じレベルのモデルと言えるか疑問だったが、Weatherのモデルが`WeatherResponseModel`となっているので問題なし

2024-08-09 03:40 UTC, Yamasaki-pan961 commented on lib/model/weather_error.dart
> +  final String? message;
![imo-badge](https://img.shields.io/badge/review-imo-skyblue) 
全ての例外クラスはmessageを持っていた方よかったりしますか？
`WeatherException`で共通でプロパティを持ったりすると良いのかな？と思いました。

2024-08-09 03:40 UTC, Yamasaki-pan961 commented on lib/domain/weather_service.dart
>          throw const FormatException();
![nits-badge](https://img.shields.io/badge/review-nits-pink)
エラーメッセージ追加しますか！

2024-08-09 03:40 UTC, Yamasaki-pan961 commented on lib/domain/weather_service.dart
> +  WeatherResponseModel fetch(WeatherParameterModel model) {
![imo-badge](https://img.shields.io/badge/review-imo-skyblue) 
パプリックメソッドは上の方に書いてくほうが見やすくなっていいかもと思いました。

自分でもメソッドの並べ方に明確な基準を持っていないですが、その時に見やすい形考えて並べることがあります。

2024-08-09 03:41 UTC, Yamasaki-pan961 requested changes
間違えてApproveしちゃったので変更要求しておきます。

2024-08-09 05:17 UTC, fa0311 commented on lib/model/weather_model.dart
> +}
> Weatherのモデルと同じレベルのモデルと言えるか疑問だったが

どういうことですか？

2024-08-09 05:25 UTC, fa0311 commented on lib/model/weather_error.dart
> +  final String? message;
`YumemiWeather.fetchWeather` で発生するエラーが `FormatException` などと比べると取得できるエラーの詳細が著しく少ないため分けていました
`message`はnullを許容するため、指摘の通り共通で持っていても問題ない気がします

2024-08-09 06:24 UTC, Yamasaki-pan961 commented on lib/model/weather_model.dart
> +}
> Weatherのモデルと同じレベルのモデルと言えるか疑問だったが

WeatherParameterModelがデータ取得領域の範囲で扱われるモデルのようにみえるため、アプリのドメイン的なモデルを意味しているように見える`weather_model.dart`に含まれていいのか？
ということでした。

この時点でアーキテクチャを定めていないので`weather_model.dart`にどのようなモデルを格納するかというのは不問としようと思い、メモに留めていたって感じです！
よって問題ないです！

2024-08-09 06:57 UTC, Yamasaki-pan961 commented on analysis_options.yaml
> +    invalid_annotation_target: ignore
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)
ファイル末尾の改行が必要な理由
https://qiita.com/hamacccccchan/items/11c17c7412a5aeb2ad74

2024-08-09 07:20 UTC, Yamasaki-pan961 reviewed
追加でコメントしました！

2024-08-09 07:20 UTC, Yamasaki-pan961 commented on cspell.json
![good-badge](https://img.shields.io/badge/Review-Good-yellow)
😍

2024-08-09 07:20 UTC, Yamasaki-pan961 commented on .vscode/settings.json
![good-badge](https://img.shields.io/badge/Review-Good-yellow)
フォーマット設定いいですね！！

2024-08-09 07:20 UTC, Yamasaki-pan961 commented on lib/model/weather_error.dart
> +class WeatherInvalidParameterException implements WeatherException {
![imo-badge](https://img.shields.io/badge/review-imo-skyblue) 
`implements`ではなく`extends`でも問題ないかな？と思ったのですがどうでしょうか？
そうすると`@override`が省略できそうです。

2024-08-09 07:20 UTC, Yamasaki-pan961 commented on lib/view/weather.dart
> +      _showAlertDialog();
![nits-badge](https://img.shields.io/badge/review-nits-pink)
WeatherExceptionに`message`や`source`が追加されたので`WeatherException`のキャッチだけに省略できそうです。

2024-08-09 08:01 UTC, fa0311 commented on lib/view/weather.dart
> +      _showAlertDialog();
https://github.com/fa0311/flutter-training/commit/bc46abc78e5177c38509aa581d9a2bd5090125ef で修正しました！

2024-08-09 08:01 UTC, fa0311 commented on lib/model/weather_error.dart
> +class WeatherInvalidParameterException implements WeatherException {
ですね！FlutterやDartなどで定義されている `Exception` はなぜかほぼ `implements` で書かれていたのでこうしました
が、冗長になるだけなので `extends` で良い気がします
https://github.com/fa0311/flutter-training/commit/bc46abc78e5177c38509aa581d9a2bd5090125ef で修正しました！

2024-08-09 08:41 UTC, Yamasaki-pan961 commented on lib/model/weather_error.dart
> +class WeatherException implements Exception {
![imo-badge](https://img.shields.io/badge/review-imo-skyblue) 
直接インスタンス化することがなさそうなので`abstract class`にしてもいいと思いました。

2024-08-09 08:59 UTC, fa0311 commented on lib/model/weather_error.dart
> +class WeatherException implements Exception {
ありがとうございます！https://github.com/fa0311/flutter-training/pull/23/commits/69e5425f6039123256a0d5471e166968ba65df4f で修正しました！

2024-08-09 09:31 UTC, Yamasaki-pan961 commented on analysis_options.yaml
> +    invalid_annotation_target: ignore
直してくださっているのでResolveします！

2024-08-09 09:32 UTC, Yamasaki-pan961 approved these changes
修正対応ありがとうございました！！
LGTMです

2024-08-09 09:32 UTC, merged