Session11: スレッドブロック
fa0311/flutter-training pull request #30
Opened 2024-08-23 04:30 UTC by fa0311

## 課題

close #12

## 対応箇所

- [x] 使用する API を `fetchWeather()` から `syncFetchWeather()` に変更する
- [x] API の処理が戻るまで [CircularProgressIndicator] を表示する

## 動作

| expected | actual |
|----------|--------|
| ![demo]      | ![画面収録 2024-08-23 13 26 36](https://github.com/user-attachments/assets/4102e849-8ced-47b6-9d5e-669378e74f4b)    |

[demo]: https://github.com/yumemi-inc/flutter-training-template/blob/main/docs/sessions/images/thread_block/demo.gif?raw=true

2024-08-23 04:54 UTC, fa0311 commented on lib/service/weather_service.dart
> -      final response = _client.fetchWeather(jsonString);
https://docs.flutter.dev/perf/isolates#web-platforms-and-compute
モバイル上では `Isolate.run` と `compute` は同等

2024-08-23 04:58 UTC, fa0311 commented on lib/view/weather.dart
> +          throw Exception('unreachable');
`StateError` を発生させるべきか悩んだ

2024-08-23 05:01 UTC, fa0311 commented on test/controller/weather_controller_test.dart
> +    final completer = Completer<WeatherResponseModel>();
`Completer` を使用して非同期処理のテストを行なっている
意図したタイミングで `Future` を終わらせることができる

2024-08-27 02:45 UTC, Yamasaki-pan961 requested changes
コメントしました！

2024-08-27 02:45 UTC, Yamasaki-pan961 commented on lib/controller/weather_controller.dart
> +      return ref.read(fetchWeatherProvider(param).future);
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen)
ここは何も返さない`return`のみ場合とどう違うのでしょう？

あと、例外が発生した時にキャッチされないです。

2024-08-27 02:45 UTC, Yamasaki-pan961 commented on lib/view/weather.dart
> +          throw Exception('unreachable');
このswitch-caseはなくてもコンパイルできると思います！

2024-08-27 02:45 UTC, Yamasaki-pan961 commented on lib/view/weather.dart
> +            context: context,
![must-badge](https://img.shields.io/badge/review-must-red)
ローディング表示中にタップをすることで表示が消えてしまいます！

2024-08-27 02:45 UTC, Yamasaki-pan961 commented on test/test_util/finder.dart
> +}
![nits-badge](https://img.shields.io/badge/review-nits-pink)
どこからも使われていないクラスです

2024-08-27 02:45 UTC, Yamasaki-pan961 commented on test/controller/weather_controller_test.dart
> +    expect(value3.isLoading, false);
![imo-badge](https://img.shields.io/badge/review-imo-skyblue) 
こんな感じに書くとわかりやすいかもです

```dart

    // CompleterでAPIの返却を制御する
    final completer = Completer<WeatherResponseModel>();
    when(mock.fetch(any)).thenAnswer((_) => completer.future);

    // 初期値がnullであることの確認
    final value0 = await container.read(weatherNotifierProvider.future);
    expect(value0, null);

    // fetchの呼び出し中はローディングであることを確認
    final firstCall =
        container.read(weatherNotifierProvider.notifier).fetch(param);
    final value1 = container.read(weatherNotifierProvider);
    expect(value1.isLoading, true);

    // ローディング中にもう一度fetchを呼び出す
    unawaited(container.read(weatherNotifierProvider.notifier).fetch(param));
    final value2 = container.read(weatherNotifierProvider);
    expect(value2.isLoading, true);

    // APIを返却させた後、ローディング状態が終了している
    completer.complete(response);
    await firstCall;
    final value3 = container.read(weatherNotifierProvider);
    expect(value3.isLoading, false);

    verify(mock.fetch(any)).called(1);
```

2024-08-27 02:45 UTC, Yamasaki-pan961 commented on test/controller/weather_controller_test.dart
> +  test('controllerのfetchで例外が発生したとき', () async {
![nits-badge](https://img.shields.io/badge/review-nits-pink)
`WeatherService.fetchで例外が発生したとき`が適切だと思います！

2024-08-27 02:45 UTC, Yamasaki-pan961 commented on test/controller/weather_controller_test.dart
> +    await container.read(weatherNotifierProvider.notifier).fetch(param);
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)
ここの挙動がよくわからなかった。
↓ローディングがtrueのまま
```dart
await completer.future;
```

↓ローティングがfalseになる

```dart
await container.read(weatherNotifierProvider.notifier).fetch(param);
```


```dart
await completer.future;
await completer.future;
```

2024-08-27 04:38 UTC, fa0311 commented on lib/controller/weather_controller.dart
> +      return ref.read(fetchWeatherProvider(param).future);
> ここは何も返さないreturnのみ場合とどう違うのでしょう？

`state` の状態によって返り値が大きく変わってしまうのを避けたかったためです。
`state` がローディング中ならすでに進行中の `Future` を返してあげることで返り値の意味を大きく変わらないと思いました

2024-08-27 05:16 UTC, Yamasaki-pan961 commented on lib/view/weather.dart
> +          throw Exception('unreachable');
↑AsyncValueがsealed classではないので`next.map`を使って記述すると良さそうです

2024-08-27 05:39 UTC, fa0311 commented on lib/controller/weather_controller.dart
> +      return ref.read(fetchWeatherProvider(param).future);
https://github.com/fa0311/flutter-training/pull/30/commits/596be69b119c05bdb2cb26969eb0eacee824cb8a で修正しました！

2024-08-27 05:40 UTC, fa0311 commented on lib/view/weather.dart
> +            context: context,
https://github.com/fa0311/flutter-training/pull/30/commits/5a04badc761e9c28a4bf4ac114710c2daa5eefa1 で修正しました！

2024-08-27 05:40 UTC, fa0311 commented on test/controller/weather_controller_test.dart
> +    expect(value3.isLoading, false);
https://github.com/fa0311/flutter-training/pull/30/commits/3e86fa9a133307c2b80020434ac1d88bc5ff18e3 で修正しました！

2024-08-27 05:51 UTC, Yamasaki-pan961 approved these changes
![LGTM](https://image.lgtmoon.dev/263411)

2024-08-27 05:52 UTC, merged